require('./common/materia-namespace')
require('./materia/materia.coms.json')
require('./materia/materia.flashcheck')
require('./materia/materia.image')
require('./materia/materia.page.default')
require('./materia/materia.set.throbber')
require('./materia/materia.store.slideshow')
require('./materia/materia.user')
require('./materia/materia.util')
require('./materia/materia.validate.textfield')
require('./common/materia-constants')
require('./controllers/ctrl-alert')
require('./controllers/ctrl-user-current')
require('./controllers/ctrl-user-login')
require('./controllers/ctrl-user-notification')
require('./controllers/ctrl-home-page-spotlight')
require('./controllers/ctrl-widget-catalog')
require('./controllers/ctrl-widget-catalog-details')
require('./services/srv-datetime')
require('./services/srv-please')
require('./services/srv-selectedwidget')
require('./services/srv-user')
require('./services/srv-widget')
require('ngmodal/dist/ng-modal.min.js')

// Materia Server common file used on all pages
