require('./controllers/ctrl-widget-player')
require('./controllers/ctrl-user-profile')
require('./controllers/ctrl-score-page')
require('./controllers/ctrl-user-settings')
require('./directives/dir-beardable')
require('./directives/dir-datatable')
require('./directives/dir-date-validation')
require('./directives/dir-fullscreen')
require('./directives/dir-ngenter')
require('./directives/dir-scoregraph')
require('./directives/dir-scoretable')
require('./materia/materia.scores.scoregraphics')
require('./services/srv-api')
require('./services/srv-scores')

// Materia Server scripts used on all player or student pages
